export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const CHANGE_START_DATE = 'CHANGE_START_DATE';
export const CHANGE_END_DATE = 'CHANGE_END_DATE';
export const CHANGE_SELECTED_TITLE = 'CHANGE_SELECTED_TITLE';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_WITH_ID = 'ADD_COMMENT_WITH_ID';
export const ADD_COMMENT_ID_IN_ARTICLE = 'ADD_COMMENT_ID_IN_ARTICLE';