export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const CHANGE_START_DATE = 'CHANGE_START_DATE';
export const CHANGE_END_DATE = 'CHANGE_END_DATE';
export const CHANGE_SELECTED_TITLE = 'CHANGE_SELECTED_TITLE';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const ADD_COMMENT = 'ADD_COMMENT';
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES';
export const LOAD_ARTICLE = 'LOAD_ARTICLE';
export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const FETCH_COMMENTS_FOR_PAGINATION = 'FETCH_COMMENTS_FOR_PAGINATION';

export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';