export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const CHANGE_START_DATE = 'CHANGE_START_DATE';
export const CHANGE_END_DATE = 'CHANGE_END_DATE';
export const CHANGE_SELECTED_TITLE = 'CHANGE_SELECTED_TITLE';